name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
      
    - name: Build with Maven
      run: |
        mvn -B clean compile package --file token/pom.xml

    - name: Store artifact
      run: |
        mkdir artifacts
        cp token/target/*.jar artifacts/

    - name: Commit and push artifact
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        git add artifacts/
        git commit -m "Add built artifact"
        git push origin HEAD:refs/heads/main

    - name: Compile and Run Java Program
      run: |
        java -cp token/target/Firebase-0.0.1-SNAPSHOT.jar com.google.firebase.samples.config.TemplateConfigure
